### ISSUE TITLE
ValueError: Using default_file_mode other than 'r' is no longer supported. Pass the mode to h5py.File() instead. JAX branch.

### ISSUE THREAD

**Issue by blenderben2** [deepmind/ferminet#32]
Hi, I am trying to run (with the JAX branch):
```
ferminet --config ferminet/configs/atom.py --config.system.atom Li --config.batch_size 256 --config.pretrain.iterations 100
```
I am getting this error:

> ValueError: Using default_file_mode other than 'r' is no longer supported. Pass the mode to h5py.File() instead.

Here is the full error:

> Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/sch_eqn/bin/ferminet", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ben/Documents/sch_eqn/ferminet_jax/bin/ferminet", line 21, in <module>
    from ferminet import train
  File "/home/ben/Documents/sch_eqn/ferminet_jax/ferminet/train.py", line 25, in <module>
    from ferminet import hamiltonian
  File "/home/ben/Documents/sch_eqn/ferminet_jax/ferminet/hamiltonian.py", line 17, in <module>
    from ferminet import networks
  File "/home/ben/Documents/sch_eqn/ferminet_jax/ferminet/networks.py", line 21, in <module>
    from ferminet.utils import scf
  File "/home/ben/Documents/sch_eqn/ferminet_jax/ferminet/utils/scf.py", line 38, in <module>
    import pyscf
  File "/home/ben/miniconda3/envs/sch_eqn/lib/python3.7/site-packages/pyscf/__init__.py", line 71, in <module>
    from pyscf import lib
  File "/home/ben/miniconda3/envs/sch_eqn/lib/python3.7/site-packages/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/home/ben/miniconda3/envs/sch_eqn/lib/python3.7/site-packages/pyscf/lib/numpy_helper.py", line 27, in <module>
    from pyscf.lib import misc
  File "/home/ben/miniconda3/envs/sch_eqn/lib/python3.7/site-packages/pyscf/lib/misc.py", line 46, in <module>
    h5py.get_config().default_file_mode = 'a'
  File "h5py/h5.pyx", line 179, in h5py.h5.H5PYConfig.default_file_mode.__set__
ValueError: Using default_file_mode other than 'r' is no longer supported. Pass the mode to h5py.File() instead.

**Comment by jsspencer** [comment]
This is fixed upstream in pyscf but is not released on PyPI. For now, please pin the version of h5py (see #31, which we'll merge soon).
